-- Infrastructure expansion of devops_access_tracking (Project Workspace Phase 2, Milestone 3)
ALTER TABLE "devops_access_tracking"
  ADD COLUMN "git_provider" TEXT,
  ADD COLUMN "git_repo_url" TEXT,
  ADD COLUMN "git_organization" TEXT,
  ADD COLUMN "git_default_branch" TEXT,
  ADD COLUMN "hosting_provider" TEXT,
  ADD COLUMN "hosting_environment" TEXT,
  ADD COLUMN "hosting_server" TEXT,
  ADD COLUMN "hosting_region" TEXT,
  ADD COLUMN "domain_name" TEXT,
  ADD COLUMN "domain_dns_provider" TEXT,
  ADD COLUMN "domain_ssl_status" TEXT,
  ADD COLUMN "domain_expiry_date" TIMESTAMP(3),
  ADD COLUMN "database_provider" TEXT,
  ADD COLUMN "database_version" TEXT,
  ADD COLUMN "database_backup_status" TEXT,
  ADD COLUMN "storage_provider" TEXT,
  ADD COLUMN "cdn_provider" TEXT,
  ADD COLUMN "smtp_provider" TEXT,
  ADD COLUMN "third_party_services" TEXT,
  ADD COLUMN "api_keys_status" TEXT NOT NULL DEFAULT 'NOT_APPLICABLE',
  ADD COLUMN "point_of_contact" TEXT,
  ADD COLUMN "credentials_verified_date" TIMESTAMP(3);
