/**
 * Canonical permission key registry.
 * Format: "{workspace}.{module}.{action}"
 *
 * Super Admin always bypasses all checks — no rows needed for SUPER_ADMIN.
 * Any role not listed in a module defaults to DENY.
 */

export const WORKSPACES = {
  ERP: 'erp',
  CRM: 'crm',
  HR:  'hr',
};

export const ACTIONS = {
  VIEW:    'view',
  CREATE:  'create',
  EDIT:    'edit',
  DELETE:  'delete',
  APPROVE: 'approve',
  EXPORT:  'export',
  ASSIGN:  'assign',
  MANAGE:  'manage',
  PUBLISH: 'publish',
  CONVERT: 'convert',
};

// Full permission key list — used to seed defaults and render the permissions UI
export const PERMISSION_DEFINITIONS = [
  // ── ERP Workspace access ──────────────────────────────────────────────────
  { key: 'erp.workspace.access',         label: 'ERP Workspace Access',     workspace: 'erp', module: 'workspace',       action: 'access' },
  { key: 'erp.dashboard.view',           label: 'ERP Dashboard',            workspace: 'erp', module: 'dashboard',        action: 'view'   },
  { key: 'erp.projects.view',            label: 'Projects – View',          workspace: 'erp', module: 'projects',         action: 'view'   },
  { key: 'erp.projects.create',          label: 'Projects – Create',        workspace: 'erp', module: 'projects',         action: 'create' },
  { key: 'erp.projects.edit',            label: 'Projects – Edit',          workspace: 'erp', module: 'projects',         action: 'edit'   },
  { key: 'erp.projects.delete',          label: 'Projects – Delete',        workspace: 'erp', module: 'projects',         action: 'delete' },
  { key: 'erp.timesheet.view',           label: 'Timesheet – View',         workspace: 'erp', module: 'timesheet',        action: 'view'   },
  { key: 'erp.timesheet.edit',           label: 'Timesheet – Edit',         workspace: 'erp', module: 'timesheet',        action: 'edit'   },
  { key: 'erp.timesheet.approve',        label: 'Timesheet – Approve',      workspace: 'erp', module: 'timesheet',        action: 'approve'},
  { key: 'erp.timesheet.export',         label: 'Timesheet – Export',       workspace: 'erp', module: 'timesheet',        action: 'export' },
  { key: 'erp.teams.view',              label: 'Teams – View',              workspace: 'erp', module: 'teams',            action: 'view'   },
  { key: 'erp.teams.create',            label: 'Teams – Create',            workspace: 'erp', module: 'teams',            action: 'create' },
  { key: 'erp.teams.edit',              label: 'Teams – Edit',              workspace: 'erp', module: 'teams',            action: 'edit'   },
  { key: 'erp.teams.delete',            label: 'Teams – Delete',            workspace: 'erp', module: 'teams',            action: 'delete' },
  { key: 'erp.users.view',              label: 'Users – View',              workspace: 'erp', module: 'users',            action: 'view'   },
  { key: 'erp.users.create',            label: 'Users – Create',            workspace: 'erp', module: 'users',            action: 'create' },
  { key: 'erp.users.edit',              label: 'Users – Edit',              workspace: 'erp', module: 'users',            action: 'edit'   },
  { key: 'erp.users.delete',            label: 'Users – Delete',            workspace: 'erp', module: 'users',            action: 'delete' },
  { key: 'erp.reports.view',            label: 'Reports – View',            workspace: 'erp', module: 'reports',          action: 'view'   },
  { key: 'erp.reports.export',          label: 'Reports – Export',          workspace: 'erp', module: 'reports',          action: 'export' },
  { key: 'erp.operations.view',         label: 'Operations – View',         workspace: 'erp', module: 'operations',       action: 'view'   },
  { key: 'erp.operations.edit',         label: 'Operations – Edit',         workspace: 'erp', module: 'operations',       action: 'edit'   },
  { key: 'erp.monitoring.view',         label: 'Monitoring – View',         workspace: 'erp', module: 'monitoring',       action: 'view'   },
  { key: 'erp.departments.view',        label: 'Departments – View',        workspace: 'erp', module: 'departments',      action: 'view'   },
  { key: 'erp.departments.create',      label: 'Departments – Create',      workspace: 'erp', module: 'departments',      action: 'create' },
  { key: 'erp.departments.edit',        label: 'Departments – Edit',        workspace: 'erp', module: 'departments',      action: 'edit'   },
  { key: 'erp.designations.view',       label: 'Designations – View',       workspace: 'erp', module: 'designations',     action: 'view'   },
  { key: 'erp.designations.create',     label: 'Designations – Create',     workspace: 'erp', module: 'designations',     action: 'create' },
  { key: 'erp.designations.edit',       label: 'Designations – Edit',       workspace: 'erp', module: 'designations',     action: 'edit'   },
  { key: 'erp.grades.view',             label: 'Grades – View',             workspace: 'erp', module: 'grades',           action: 'view'   },
  { key: 'erp.grades.create',           label: 'Grades – Create',           workspace: 'erp', module: 'grades',           action: 'create' },
  { key: 'erp.grades.edit',             label: 'Grades – Edit',             workspace: 'erp', module: 'grades',           action: 'edit'   },
  { key: 'erp.performance.view',        label: 'Performance – View',        workspace: 'erp', module: 'performance',      action: 'view'   },
  { key: 'erp.performance.approve',     label: 'Performance – Approve',     workspace: 'erp', module: 'performance',      action: 'approve'},
  { key: 'erp.assets.view',             label: 'Assets – View',             workspace: 'erp', module: 'assets',           action: 'view'   },
  { key: 'erp.assets.create',           label: 'Assets – Create',           workspace: 'erp', module: 'assets',           action: 'create' },
  { key: 'erp.assets.edit',             label: 'Assets – Edit',             workspace: 'erp', module: 'assets',           action: 'edit'   },
  { key: 'erp.assets.delete',           label: 'Assets – Delete',           workspace: 'erp', module: 'assets',           action: 'delete' },
  { key: 'erp.requisitions.view',       label: 'Requisitions – View',       workspace: 'erp', module: 'requisitions',     action: 'view'   },
  { key: 'erp.requisitions.create',     label: 'Requisitions – Create',     workspace: 'erp', module: 'requisitions',     action: 'create' },
  { key: 'erp.requisitions.approve',    label: 'Requisitions – Approve',    workspace: 'erp', module: 'requisitions',     action: 'approve'},
  { key: 'erp.attendance.view',         label: 'Attendance – View',         workspace: 'erp', module: 'attendance',       action: 'view'   },
  { key: 'erp.attendance.edit',         label: 'Attendance – Edit',         workspace: 'erp', module: 'attendance',       action: 'edit'   },
  { key: 'erp.estimator.view',          label: 'Estimator – View',          workspace: 'erp', module: 'estimator',        action: 'view'   },
  { key: 'erp.permissions.manage',      label: 'Permissions Management',    workspace: 'erp', module: 'permissions',      action: 'manage' },
  { key: 'erp.expenses.view',           label: 'Expenses – View',           workspace: 'erp', module: 'expenses',          action: 'view'   },
  { key: 'erp.expenses.create',         label: 'Expenses – Create',         workspace: 'erp', module: 'expenses',          action: 'create' },
  { key: 'erp.expenses.edit',           label: 'Expenses – Edit',           workspace: 'erp', module: 'expenses',          action: 'edit'   },
  { key: 'erp.expenses.delete',         label: 'Expenses – Delete',         workspace: 'erp', module: 'expenses',          action: 'delete' },
  { key: 'erp.expenses.manage',         label: 'Expenses – Manage',         workspace: 'erp', module: 'expenses',          action: 'manage' },

  // ── CRM Workspace access ──────────────────────────────────────────────────
  { key: 'crm.workspace.access',        label: 'CRM Workspace Access',      workspace: 'crm', module: 'workspace',        action: 'access' },
  { key: 'crm.dashboard.view',          label: 'CRM Dashboard',             workspace: 'crm', module: 'dashboard',        action: 'view'   },
  { key: 'crm.pipeline.view',           label: 'Pipeline – View',           workspace: 'crm', module: 'pipeline',         action: 'view'   },
  { key: 'crm.pipeline.create',         label: 'Pipeline – Create',         workspace: 'crm', module: 'pipeline',         action: 'create' },
  { key: 'crm.pipeline.edit',           label: 'Pipeline – Edit',           workspace: 'crm', module: 'pipeline',         action: 'edit'   },
  { key: 'crm.pipeline.delete',         label: 'Pipeline – Delete',         workspace: 'crm', module: 'pipeline',         action: 'delete' },
  { key: 'crm.upwork.view',             label: 'Upwork Bids – View',        workspace: 'crm', module: 'upwork',           action: 'view'   },
  { key: 'crm.upwork.create',           label: 'Upwork Bids – Create',      workspace: 'crm', module: 'upwork',           action: 'create' },
  { key: 'crm.upwork.edit',             label: 'Upwork Bids – Edit',        workspace: 'crm', module: 'upwork',           action: 'edit'   },
  { key: 'crm.linkedin.view',           label: 'LinkedIn Leads – View',     workspace: 'crm', module: 'linkedin',         action: 'view'   },
  { key: 'crm.linkedin.create',         label: 'LinkedIn Leads – Create',   workspace: 'crm', module: 'linkedin',         action: 'create' },
  { key: 'crm.linkedin.edit',           label: 'LinkedIn Leads – Edit',     workspace: 'crm', module: 'linkedin',         action: 'edit'   },
  { key: 'crm.email_leads.view',        label: 'Email Leads – View',        workspace: 'crm', module: 'email_leads',      action: 'view'   },
  { key: 'crm.email_leads.create',      label: 'Email Leads – Create',      workspace: 'crm', module: 'email_leads',      action: 'create' },
  { key: 'crm.email_leads.edit',        label: 'Email Leads – Edit',        workspace: 'crm', module: 'email_leads',      action: 'edit'   },
  { key: 'crm.won_deals.view',          label: 'Won Deals – View',          workspace: 'crm', module: 'won_deals',        action: 'view'   },
  { key: 'crm.won_deals.create',        label: 'Won Deals – Create',        workspace: 'crm', module: 'won_deals',        action: 'create' },
  { key: 'crm.won_deals.convert',       label: 'Won Deals – Convert',       workspace: 'crm', module: 'won_deals',        action: 'convert'},
  { key: 'crm.deposits.view',           label: 'Deposits – View',           workspace: 'crm', module: 'deposits',         action: 'view'   },
  { key: 'crm.deposits.create',         label: 'Deposits – Create',         workspace: 'crm', module: 'deposits',         action: 'create' },
  { key: 'crm.targets.view',            label: 'Targets – View',            workspace: 'crm', module: 'targets',          action: 'view'   },
  { key: 'crm.targets.edit',            label: 'Targets – Edit',            workspace: 'crm', module: 'targets',          action: 'edit'   },
  { key: 'crm.invoices.view',           label: 'Invoices – View',           workspace: 'crm', module: 'invoices',         action: 'view'   },
  { key: 'crm.invoices.create',         label: 'Invoices – Create',         workspace: 'crm', module: 'invoices',         action: 'create' },
  { key: 'crm.invoices.approve',        label: 'Invoices – Approve',        workspace: 'crm', module: 'invoices',         action: 'approve'},
  { key: 'crm.handoffs.view',           label: 'Handoffs – View',           workspace: 'crm', module: 'handoffs',         action: 'view'   },
  { key: 'crm.handoffs.create',         label: 'Handoffs – Create',         workspace: 'crm', module: 'handoffs',         action: 'create' },
  { key: 'crm.salary.view',             label: 'Salary Builder – View',     workspace: 'crm', module: 'salary',           action: 'view'   },
  { key: 'crm.salary.edit',             label: 'Salary Builder – Edit',     workspace: 'crm', module: 'salary',           action: 'edit'   },
  { key: 'crm.salary.approve',          label: 'Salary Builder – Approve',  workspace: 'crm', module: 'salary',           action: 'approve'},
  { key: 'crm.reports.view',            label: 'CRM Reports – View',        workspace: 'crm', module: 'reports',          action: 'view'   },
  { key: 'crm.reports.export',          label: 'CRM Reports – Export',      workspace: 'crm', module: 'reports',          action: 'export' },

  // ── HR Workspace access ───────────────────────────────────────────────────
  { key: 'hr.workspace.access',         label: 'HR Workspace Access',       workspace: 'hr',  module: 'workspace',        action: 'access' },
  { key: 'hr.dashboard.view',           label: 'HR Dashboard',              workspace: 'hr',  module: 'dashboard',        action: 'view'   },
  { key: 'hr.employees.view',           label: 'Employees – View',          workspace: 'hr',  module: 'employees',        action: 'view'   },
  { key: 'hr.employees.create',         label: 'Employees – Create',        workspace: 'hr',  module: 'employees',        action: 'create' },
  { key: 'hr.employees.edit',           label: 'Employees – Edit',          workspace: 'hr',  module: 'employees',        action: 'edit'   },
  { key: 'hr.employees.delete',         label: 'Employees – Delete',        workspace: 'hr',  module: 'employees',        action: 'delete' },
  { key: 'hr.departments.view',         label: 'HR Departments – View',     workspace: 'hr',  module: 'departments',      action: 'view'   },
  { key: 'hr.departments.edit',         label: 'HR Departments – Edit',     workspace: 'hr',  module: 'departments',      action: 'edit'   },
  { key: 'hr.attendance.view',          label: 'HR Attendance – View',      workspace: 'hr',  module: 'attendance',       action: 'view'   },
  { key: 'hr.attendance.approve',       label: 'HR Attendance – Approve',   workspace: 'hr',  module: 'attendance',       action: 'approve'},
  { key: 'hr.timesheet.view',           label: 'HR Timesheet – View',       workspace: 'hr',  module: 'timesheet',        action: 'view'   },
  { key: 'hr.timesheet.approve',        label: 'HR Timesheet – Approve',    workspace: 'hr',  module: 'timesheet',        action: 'approve'},
  { key: 'hr.performance.view',         label: 'HR Performance – View',     workspace: 'hr',  module: 'performance',      action: 'view'   },
  { key: 'hr.performance.approve',      label: 'HR Performance – Approve',  workspace: 'hr',  module: 'performance',      action: 'approve'},
  { key: 'hr.assets.view',              label: 'HR Assets – View',          workspace: 'hr',  module: 'assets',           action: 'view'   },
  { key: 'hr.assets.manage',            label: 'HR Assets – Manage',        workspace: 'hr',  module: 'assets',           action: 'manage' },
  { key: 'hr.requisitions.view',        label: 'HR Requisitions – View',    workspace: 'hr',  module: 'requisitions',     action: 'view'   },
  { key: 'hr.requisitions.approve',     label: 'HR Requisitions – Approve', workspace: 'hr',  module: 'requisitions',     action: 'approve'},
  { key: 'hr.contracts.view',           label: 'Contracts – View',          workspace: 'hr',  module: 'contracts',        action: 'view'   },
  { key: 'hr.contracts.create',         label: 'Contracts – Create',        workspace: 'hr',  module: 'contracts',        action: 'create' },
  { key: 'hr.contracts.edit',           label: 'Contracts – Edit',          workspace: 'hr',  module: 'contracts',        action: 'edit'   },
  { key: 'hr.onboarding.view',          label: 'Onboarding – View',         workspace: 'hr',  module: 'onboarding',       action: 'view'   },
  { key: 'hr.onboarding.manage',        label: 'Onboarding – Manage',       workspace: 'hr',  module: 'onboarding',       action: 'manage' },
  { key: 'hr.policies.view',            label: 'Policies – View',           workspace: 'hr',  module: 'policies',         action: 'view'   },
  { key: 'hr.policies.manage',          label: 'Policies – Manage',         workspace: 'hr',  module: 'policies',         action: 'manage' },
  { key: 'hr.job_descriptions.view',    label: 'Job Descriptions – View',   workspace: 'hr',  module: 'job_descriptions', action: 'view'   },
  { key: 'hr.job_descriptions.manage',  label: 'Job Descriptions – Manage', workspace: 'hr',  module: 'job_descriptions', action: 'manage' },
  { key: 'hr.salary.view',              label: 'HR Salary – View',          workspace: 'hr',  module: 'salary',           action: 'view'   },
  { key: 'hr.salary.edit',              label: 'HR Salary – Edit',          workspace: 'hr',  module: 'salary',           action: 'edit'   },
  { key: 'hr.salary.approve',           label: 'HR Salary – Approve',       workspace: 'hr',  module: 'salary',           action: 'approve'},
  { key: 'hr.employee_profiles.view',   label: 'Employee Profiles – View',  workspace: 'hr',  module: 'employee_profiles',action: 'view'   },
  { key: 'hr.employee_profiles.edit',   label: 'Employee Profiles – Edit',  workspace: 'hr',  module: 'employee_profiles',action: 'edit'   },
];

// Default grants per role.
// Super Admin is not listed — they bypass permission checks entirely.
export const DEFAULT_ROLE_PERMISSIONS = {
  ADMIN: [
    'erp.workspace.access', 'erp.dashboard.view',
    'erp.projects.view', 'erp.projects.create', 'erp.projects.edit', 'erp.projects.delete',
    'erp.timesheet.view', 'erp.timesheet.edit', 'erp.timesheet.approve', 'erp.timesheet.export',
    'erp.teams.view', 'erp.teams.create', 'erp.teams.edit', 'erp.teams.delete',
    'erp.users.view', 'erp.users.create', 'erp.users.edit',
    'erp.reports.view', 'erp.reports.export',
    'erp.operations.view', 'erp.operations.edit',
    'erp.monitoring.view',
    'erp.departments.view', 'erp.departments.create', 'erp.departments.edit',
    'erp.designations.view', 'erp.designations.create', 'erp.designations.edit',
    'erp.grades.view', 'erp.grades.create', 'erp.grades.edit',
    'erp.performance.view', 'erp.performance.approve',
    'erp.assets.view', 'erp.assets.create', 'erp.assets.edit', 'erp.assets.delete',
    'erp.requisitions.view', 'erp.requisitions.create', 'erp.requisitions.approve',
    'erp.attendance.view', 'erp.attendance.edit',
    'erp.estimator.view',
    'erp.expenses.view', 'erp.expenses.create', 'erp.expenses.edit', 'erp.expenses.delete', 'erp.expenses.manage',
    'hr.workspace.access', 'hr.dashboard.view',
    'hr.employees.view', 'hr.employees.create', 'hr.employees.edit',
    'hr.departments.view', 'hr.departments.edit',
    'hr.attendance.view', 'hr.attendance.approve',
    'hr.timesheet.view', 'hr.timesheet.approve',
    'hr.performance.view', 'hr.performance.approve',
    'hr.assets.view', 'hr.assets.manage',
    'hr.requisitions.view', 'hr.requisitions.approve',
    'hr.contracts.view', 'hr.contracts.create', 'hr.contracts.edit',
    'hr.onboarding.view', 'hr.onboarding.manage',
    'hr.policies.view', 'hr.policies.manage',
    'hr.job_descriptions.view', 'hr.job_descriptions.manage',
    'hr.salary.view',
    'hr.employee_profiles.view', 'hr.employee_profiles.edit',
  ],
  HR: [
    'hr.workspace.access', 'hr.dashboard.view',
    'hr.employees.view', 'hr.employees.create', 'hr.employees.edit',
    'hr.departments.view', 'hr.departments.edit',
    'hr.attendance.view', 'hr.attendance.approve',
    'hr.timesheet.view', 'hr.timesheet.approve',
    'hr.performance.view', 'hr.performance.approve',
    'hr.assets.view', 'hr.assets.manage',
    'hr.requisitions.view', 'hr.requisitions.approve',
    'hr.contracts.view', 'hr.contracts.create', 'hr.contracts.edit',
    'hr.onboarding.view', 'hr.onboarding.manage',
    'hr.policies.view', 'hr.policies.manage',
    'hr.job_descriptions.view', 'hr.job_descriptions.manage',
    'hr.salary.view', 'hr.salary.edit', 'hr.salary.approve',
    'hr.employee_profiles.view', 'hr.employee_profiles.edit',
    'erp.workspace.access', 'erp.dashboard.view',
    'erp.timesheet.view', 'erp.timesheet.approve',
    'erp.attendance.view', 'erp.attendance.edit',
    'erp.departments.view',
    'erp.designations.view', 'erp.designations.create', 'erp.designations.edit',
    'erp.grades.view', 'erp.grades.create', 'erp.grades.edit',
    'erp.users.view',
    'erp.reports.view',
  ],
  DIVISION_MANAGER: [
    'erp.workspace.access', 'erp.dashboard.view',
    'erp.projects.view',
    'erp.timesheet.view', 'erp.timesheet.approve',
    'erp.teams.view',
    'erp.users.view',
    'erp.reports.view', 'erp.reports.export',
    'erp.operations.view',
    'erp.monitoring.view',
    'erp.departments.view',
    'erp.designations.view',
    'erp.grades.view',
    'erp.performance.view',
    'erp.attendance.view',
    'erp.requisitions.view', 'erp.requisitions.approve',
    'hr.workspace.access',
    'hr.employees.view',
    'hr.attendance.view',
    'hr.performance.view',
    'hr.salary.view',
  ],
  // Team Lead manages a single team's day-to-day work within a division — a subset
  // of DIVISION_MANAGER scoped down from division-wide admin to just their own team:
  //  - Keeps: workspace access, dashboards, team/project visibility, attendance/
  //    timesheet visibility + approval for their team's members, and team performance
  //    visibility — mirrors what a Division Manager sees, just narrower in practice
  //    (enforced by team_id/leader_id scoping at the controller/query level, the same
  //    pattern EMPLOYEE's erp.projects.view already relies on for member_only scoping).
  //  - Adds erp.projects.edit beyond DIVISION_MANAGER: a Team Lead is the one actually
  //    editing their team's project/task details day-to-day (per projects.leader_id in
  //    the schema), whereas a Division Manager mostly reviews at a higher level.
  //  - Drops everything division/org-wide that DIVISION_MANAGER has: erp.reports.*,
  //    erp.operations.view, erp.monitoring.view, erp.departments.view,
  //    erp.designations.view, erp.grades.view, erp.users.view, and
  //    erp.requisitions.approve (budget-level sign-off stays with Division Manager).
  //  - No hr-wide employee editing and no erp.permissions.manage (permission-matrix
  //    access) — Team Lead is not an HR or admin role.
  TEAM_LEAD: [
    'erp.workspace.access', 'erp.dashboard.view',
    'erp.projects.view', 'erp.projects.edit',
    'erp.timesheet.view', 'erp.timesheet.approve',
    'erp.teams.view',
    'erp.attendance.view',
    'erp.performance.view',
    'erp.requisitions.view',
    'hr.workspace.access',
    'hr.employees.view',
  ],
  MARKETING: [
    'crm.workspace.access', 'crm.dashboard.view',
    'crm.pipeline.view', 'crm.pipeline.create', 'crm.pipeline.edit',
    'crm.upwork.view', 'crm.upwork.create', 'crm.upwork.edit',
    'crm.linkedin.view', 'crm.linkedin.create', 'crm.linkedin.edit',
    'crm.email_leads.view', 'crm.email_leads.create', 'crm.email_leads.edit',
    'crm.won_deals.view', 'crm.won_deals.create',
    'crm.deposits.view', 'crm.deposits.create',
    'crm.targets.view',
    'crm.handoffs.view', 'crm.handoffs.create',
    'crm.reports.view',
  ],
  EMPLOYEE: [
    // Employees use the /employee workspace — no ERP/CRM/HR workspace access by default
    // except projects, which the controller scopes to member_only for this role
    'erp.projects.view',
  ],
};

export const ALL_ROLE_NAMES = ['ADMIN', 'HR', 'DIVISION_MANAGER', 'TEAM_LEAD', 'MARKETING', 'EMPLOYEE'];
