ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "budget" DOUBLE PRECISION;
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "budget_currency" TEXT NOT NULL DEFAULT 'PKR';
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "budget_spent" DOUBLE PRECISION NOT NULL DEFAULT 0;
